spring.application.name=festly

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/festly
spring.datasource.username=pedro
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration