ALTER TABLE servicos ADD COLUMN cidade       VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE servicos ADD COLUMN tipo_cobranca VARCHAR(50)  NOT NULL DEFAULT 'POR_EVENTO';
ALTER TABLE servicos ADD COLUMN imagem_capa  VARCHAR(500);
